
# image: ubuntu:22.04

# services:
#   - ubuntu:22.04

stages:
  # - test
  # - sonar
  - build
  # - build_dev

variables:
  GIT_STRATEGY: none
  PROJECT_REPO_NAMESPACE: spider1
  PROJECT_REPO_NAME: spider_proxy


before_script:
  # - exec ssh-agent bash
  - eval "pwd"
  - eval "ssh-agent bash"
  - pwd
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - ls -al ~/.ssh/

  - git --version
  - git clone -b $CI_COMMIT_REF_NAME --depth=1 git@jihulab.com:$PROJECT_REPO_NAMESPACE/$PROJECT_REPO_NAME.git
  - cd $PROJECT_REPO_NAME


build:
  stage: build
  script:
    - export ROOT_PATH=$(pwd)
    - echo 'root path:' $ROOT_PATH 
    - ls -lh
    - cd docker
    # - export DATE=$(git log -1 --pretty=format:"%ad" --date=format:'%Y%m%d' $CI_COMMIT_SHA)
    - echo 'date:' $DATE
    - export DOCKER_TAG_SUFFIX="ci"_$DATE"_"${CI_COMMIT_SHA:0:8}
    - echo 'build start:' $DOCKER_TAG_SUFFIX 
    - sh build_image.sh $DOCKER_TAG_SUFFIX
    - echo 'build end:' $DOCKER_TAG_SUFFIX 
    - cd ../../
    # - rm -rf *


# build_dev_stage:
#   stage: build_dev
#   script:
#     - cd docker
#     - echo 'build start:' $DEV_DOCKER_TAG_SUFFIX 
#     - sh build_dev_image.sh $DEV_DOCKER_TAG_SUFFIX
#     - echo 'build end:' $DEV_DOCKER_TAG_SUFFIX 
  # when: manual


# git clone 项目
# build image
# push image
