
image: docker:20.10.16

services:
  - docker:20.10.16-dind

stages:
  # - test
  # - sonar
  - build
  - build_dev

variables:
  GIT_STRATEGY: none
  PROJECT_REPO_NAMESPACE: spider1
  PROJECT_REPO_NAME: spider_proxy


before_script:
  - docker info
  - docker build -t my-docker-image .

build:
  
  stage: build
  script:

    - export ROOT_PATH=$(pwd)
    - echo 'root path:' $ROOT_PATH
    - echo 'user:' $DOCKER_USER

# build_dev_stage:
#   stage: build_dev
#   script:
#     - cd docker
#     - sh build_dev_image.sh $DEV_DOCKER_TAG_SUFFIX
  # when: manual


