
image: docker:20.10.16

services:
  - docker:20.10.16-dind

stages:
  # - test
  # - sonar
  - build
  - build_dev

variables:
  GIT_STRATEGY: none
  PROJECT_REPO_NAMESPACE: spider1
  PROJECT_REPO_NAME: spider_proxy


before_script:
  - docker version
  - git --version
  # - docker login -u $DOCKER_USER -p $DOCKER_PW http://dockerhub.datagrand.com
  - echo 'CI_COMMIT_REF_NAME _value:' $CI_COMMIT_REF_NAME
  - git clone -b $CI_COMMIT_REF_NAME --depth=1 ssh://git@jihulab.com:$PROJECT_REPO_NAMESPACE/$PROJECT_REPO_NAME.git
  - cd $PROJECT_REPO_NAME
  - ls -lh

build:
  
  stage: build
  script:

    - export ROOT_PATH=$(pwd)
    - echo 'root path:' $ROOT_PATH

# build_dev_stage:
#   stage: build_dev
#   script:
#     - cd docker
#     - sh build_dev_image.sh $DEV_DOCKER_TAG_SUFFIX
  # when: manual


# git clone 项目
# build image
# push image
