stages:
  # - test
  # - sonar
  - build
  - build_debug_stage

variables:
  GIT_STRATEGY: clone
  PROJECT_REPO_NAMESPACE: spider1
  PROJECT_REPO_NAME: spider_proxy


# before_script:
  # - eval "$(ssh-agent -s)"
  # - eval "$(bash)"
  # - pwd
  # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  # - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  # - chmod 644 ~/.ssh/known_hosts
  # - ls -al ~/.ssh/
  # - git clone -b $CI_COMMIT_REF_NAME --depth=1 git@jihulab.com:$PROJECT_REPO_NAMESPACE/$PROJECT_REPO_NAME.git
  # - cd $PROJECT_REPO_NAME


build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  tags: 
    - docker
  script:
    - export ROOT_PATH=$(pwd)
    - echo 'root path:' $ROOT_PATH
    - cd docker
    - export DATE=$(git log -1 --pretty=format:"%ad" --date=format:'%Y%m%d_%H%M%S' $CI_COMMIT_SHA)
    - echo 'date:' $DATE
    - export DOCKER_TAG_SUFFIX="ci"_$DATE"_"${CI_COMMIT_SHA:0:8}
    - echo 'build start:' $DOCKER_TAG_SUFFIX  
    - export DockerImageName="workdragonfang/"$PROJECT_REPO_NAME":"$DOCKER_TAG_SUFFIX
    - bash build_image.sh $DockerImageName
    - echo 'build end image name :' $DockerImageName
    
build_debug_stage:
  stage: build_debug_stage
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  tags: 
    - docker
  script:
    - export ROOT_PATH=$(pwd)
    - echo 'root path:' $ROOT_PATH
    - cd docker
    - export DATE=$(git log -1 --pretty=format:"%ad" --date=format:'%Y%m%d_%H%M%S' $CI_COMMIT_SHA)
    - echo 'date:' $DATE
    - export DOCKER_TAG_SUFFIX="ci"_$DATE"_"${CI_COMMIT_SHA:0:8}
    - echo 'build start:' $DOCKER_TAG_SUFFIX  
    - export DockerImageName="workdragonfang/"$PROJECT_REPO_NAME":"$DOCKER_TAG_SUFFIX
    - bash build_image.sh $DockerImageName
    - echo 'build end image name :' $DockerImageName
  when: manual


# git clone 项目
# build image
# push image
