
image: docker:20.10.16

services:
  - docker:20.10.16-dind

stages:
  # - test
  # - sonar
  - build
  - build_dev

variables:
  GIT_STRATEGY: none
  PROJECT_REPO_NAMESPACE: spider1
  PROJECT_REPO_NAME: spider_proxy


before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - pwd
  - git clone -b $CI_COMMIT_REF_NAME --depth=1 git@jihulab.com:$PROJECT_REPO_NAMESPACE/$PROJECT_REPO_NAME.git
  - cd $PROJECT_REPO_NAME


build:
  
  stage: build
  script:

    - export ROOT_PATH=$(pwd)
    - echo 'root path:' $ROOT_PATH

build_dev_stage:
  stage: build_dev
  script:
    - cd docker
    - echo 'build start:' $DEV_DOCKER_TAG_SUFFIX 
    - sh build_dev_image.sh $DEV_DOCKER_TAG_SUFFIX
    - echo 'build end:' $DEV_DOCKER_TAG_SUFFIX 
  # when: manual


# git clone 项目
# build image
# push image
