"""add SpiderProxyModel

Revision ID: 726a6234a359
Revises: 
Create Date: 2023-08-02 17:29:07.215071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726a6234a359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spider_proxy',
    sa.Column('id', sa.String(length=50), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('protocol', sa.String(length=100), nullable=False, comment='类型：http https socks '),
    sa.Column('ip', sa.String(length=100), nullable=False, comment='ip'),
    sa.Column('port', sa.String(length=100), nullable=False, comment='端口'),
    sa.Column('anonymity_type', sa.String(length=100), nullable=False, comment='匿名类型：透明 匿名 高匿'),
    sa.Column('location', sa.String(length=100), nullable=False, comment='位置(归属地)'),
    sa.Column('network_operator', sa.String(length=100), nullable=False, comment='网络运营商'),
    sa.Column('useable', sa.Integer(), nullable=False, comment='是否可用'),
    sa.Column('telnet_num_1', sa.Integer(), nullable=False, comment='telnet 次数'),
    sa.Column('telnet_num_0', sa.Integer(), nullable=False, comment='telnet 次数'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spider_proxy')
    # ### end Alembic commands ###
