"""spider_proxy__total_seconds

Revision ID: e9def6cce12a
Revises: 726a6234a359
Create Date: 2023-08-05 16:19:22.799985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9def6cce12a'
down_revision = '726a6234a359'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spider_proxy', sa.Column('total_seconds', sa.Integer(), nullable=False, comment='耗时 毫秒', server_default="0"))
    # op.alter_column('spider_proxy', 'id',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=True,
    #            existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('spider_proxy', 'id',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=False,
    #            existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('spider_proxy', 'total_seconds')
    # ### end Alembic commands ###
