"""empty message

Revision ID: 3196c2252bf5
Revises: 
Create Date: 2021-12-08 18:01:40.815920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'show'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('di_down_file',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('last_update_time', sa.DATETIME(), nullable=True, comment='最近修改时间'),
    sa.Column('file_id', sa.NVARCHAR(length=100), nullable=True, comment='文件id'),
    sa.Column('audit_item_id', sa.NVARCHAR(length=100), nullable=True, comment='审核记录id'),
    sa.Column('company_full_name', sa.NVARCHAR(length=100), nullable=True, comment='发行人公司全称'),
    sa.Column('publish_date', sa.NVARCHAR(length=20), nullable=True, comment='披露日期'),
    sa.Column('file_version_code', sa.NVARCHAR(length=20), nullable=True, comment='报告类型编码'),
    sa.Column('file_version', sa.NVARCHAR(length=20), nullable=True, comment='报告类型'),
    sa.Column('file_path', sa.NVARCHAR(length=200), nullable=True, comment='网站端文件落地路径'),
    sa.Column('file_name', sa.NVARCHAR(length=100), nullable=True, comment='文件唯一名称'),
    sa.Column('file_title', sa.NVARCHAR(length=100), nullable=True, comment='披露文件的标题'),
    sa.Column('json_data', sa.NVARCHAR(length=2000), nullable=True, comment='json object data'),
    sa.Column('extract_id', sa.INTEGER(), nullable=True, comment='抽取id'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据输入接口，文件下载表'
    )
    op.create_index(op.f('ix_di_down_file_last_update_time'), 'di_down_file', ['last_update_time'], unique=False)
    op.create_table('t_idea',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('last_update_time', sa.DATETIME(), nullable=True, comment='最近修改时间'),
    sa.Column('title', sa.VARCHAR(length=255), server_default='', nullable=True, comment='备忘录标题'),
    sa.Column('level', sa.SMALLINT(), server_default=sa.text('0'), nullable=True, comment='状态'),
    sa.Column('text', sa.Text(), nullable=True, comment='备忘录内容'),
    sa.Column('is_done', sa.BOOLEAN(), server_default=sa.text('false'), nullable=True, comment='是否完成'),
    sa.Column('done_at', sa.DATETIME(), nullable=True, comment='完成时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='备忘录表'
    )
    op.create_index(op.f('ix_t_idea_last_update_time'), 't_idea', ['last_update_time'], unique=False)
    op.create_index(op.f('ix_t_idea_title'), 't_idea', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_idea_title'), table_name='t_idea')
    op.drop_index(op.f('ix_t_idea_last_update_time'), table_name='t_idea')
    op.drop_table('t_idea')
    op.drop_index(op.f('ix_di_down_file_last_update_time'), table_name='di_down_file')
    op.drop_table('di_down_file')
    # ### end Alembic commands ###
